create table if not exists public.timeblock_states (
  user_id uuid primary key references auth.users (id) on delete cascade,
  state jsonb not null,
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.timeblock_states enable row level security;

revoke all on table public.timeblock_states from anon;
grant select, insert, update on table public.timeblock_states to authenticated;

drop policy if exists "Users can read their own Timeblock state" on public.timeblock_states;
create policy "Users can read their own Timeblock state"
on public.timeblock_states for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own Timeblock state" on public.timeblock_states;
create policy "Users can insert their own Timeblock state"
on public.timeblock_states for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own Timeblock state" on public.timeblock_states;
create policy "Users can update their own Timeblock state"
on public.timeblock_states for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function public.set_timeblock_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_timeblock_updated_at on public.timeblock_states;
create trigger set_timeblock_updated_at
before update on public.timeblock_states
for each row execute function public.set_timeblock_updated_at();

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  timezone text not null,
  notify_start boolean not null default true,
  notify_end boolean not null default true,
  user_agent text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (endpoint),
  constraint push_subscriptions_endpoint_length check (char_length(endpoint) between 12 and 4096),
  constraint push_subscriptions_timezone_length check (char_length(timezone) between 1 and 80),
  constraint push_subscriptions_has_reminder check (notify_start or notify_end)
);

alter table public.push_subscriptions enable row level security;

revoke all on table public.push_subscriptions from anon;
revoke all on table public.push_subscriptions from authenticated;
grant select, insert, update, delete on table public.push_subscriptions to authenticated;

drop policy if exists "Users can read their own push subscriptions" on public.push_subscriptions;
create policy "Users can read their own push subscriptions"
on public.push_subscriptions for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own push subscriptions" on public.push_subscriptions;
create policy "Users can insert their own push subscriptions"
on public.push_subscriptions for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own push subscriptions" on public.push_subscriptions;
create policy "Users can update their own push subscriptions"
on public.push_subscriptions for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own push subscriptions" on public.push_subscriptions;
create policy "Users can delete their own push subscriptions"
on public.push_subscriptions for delete
to authenticated
using ((select auth.uid()) = user_id);

drop trigger if exists set_push_subscription_updated_at on public.push_subscriptions;
create trigger set_push_subscription_updated_at
before update on public.push_subscriptions
for each row execute function public.set_timeblock_updated_at();

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  subscription_id bigint not null references public.push_subscriptions (id) on delete cascade,
  event_key text not null,
  sent_at timestamptz not null default timezone('utc', now()),
  unique (subscription_id, event_key)
);

alter table public.push_deliveries enable row level security;
revoke all on table public.push_deliveries from anon, authenticated;
